<?php

                return array (
  'verify' => 
  array (
    'title' => 'Verify your account',
  ),
  'ajax' => 
  array (
    'login_success' => 'You are successfully logged in',
    'login_error' => 'Email and/or password invalid.',
    'otp_sent' => 'OTP Sent',
    'otp_send_error' => 'Unable to send OTP, try again later',
    'otp_error' => 'Something went wrong',
    'otp_validation' => 'Phone Number and OTP  are required',
    'otp_verify_success' => 'Verified',
    'otp_verify_error' => 'OTP Mismatch, please check and try again',
    'register_success' => 'Thank you for sign up. Please verify your email & mobile number by clicking on the link received on your email.',
    'forgot_password_success' => 'password link sent to email.',
    'social_media_login_error' => 'something went wrong!',
    'unable_to_create_account' => 'Unable to create account',
    'password_updated' => 'Password Updated',
    'otp_invalid' => 'OTP is invalid',
    'user_not_exist' => 'User does not exist',
    'user_logged_out' => 'User logged out',
    'cross_user_request' => 'Cross User Request or User logged out',
    'invalid_session' => 'Invalid Session',
    'invalid_token' => 'Invalid Token',
    'user_banned' => 'This user is banned',
    'invalid_credentials' => 'The provided credentials are incorrect.',
  ),
  'toast' => 
  array (
    'login_success' => 'You are successfully logged in',
    'logout_success' => 'You are logged out, come back soon!',
    'verify_info' => 'Your account is already verified.',
    'verify_success' => 'You have successfully verified your email, restriction is removed from your account now',
    'register_success' => 'Thank you for sign up. Please verify your email and mobile number by clicking on the link received on your email.',
    'reset_password_success' => 'Your password has been reset successfully.',
    'login_to_proceed' => 'You need to be logged in to proceed',
  ),
  'failed' => 'These credentials do not match our records.',
  'throttle' => 'Too many login attempts. Please try again in a few minutes.',
  'invalid_signature' => 'Invalid Signature',
  'button' => 
  array (
    'change_password' => 'Change Password',
    'signin' => 'Login',
    'join_now' => 'Get Started',
    'logout' => 'Logout',
  ),
  'form' => 
  array (
    'email_placeholder' => 'Email',
    'password_placeholder' => 'Enter Password',
    'existing_user' => 'Existing User',
    'note' => 'We\'ll never post anything without your permission.',
    'terms_apply' => 'Joining & Referral Bonus Terms Apply*',
    'remember_me' => 'Remember Me',
    'reset_password' => 'Reset Your Password',
    'email_valid_msg' => 'Looks Good!',
    'forgot_password_link' => 'Forgot Password?',
    'forgot_password_note' => 'Enter your email address and we will send you the instructions to reset your password',
    'time_left' => 'Time left =',
    'not_member' => 'Not Member',
    'sign_up_get' => 'Sign up & get',
    'today' => 'Today',
    'social_media_signup' => 'Welcome! You are just a click away from joining our green website.',
    'someone_refer_you' => 'Did someone refer you?',
    'enter_otp' => 'Enter OTP',
    'social_media_email_validation' => 'Enter a valid email to receive verification link',
    'agree_policy' => 'I Agree to <a href=\':PRIVACY\' class=\'text-purple\'  target=\'_blank\'> Privacy Policy</a> and <a href=\':TERMS\' class=\'text-purple\'  target=\'_blank\'>Terms of Use</a>',
    'forgot_password' => 'Forgot Password!',
    'signin' => 'Sign In',
    'send_reset_link' => 'Send Password Reset Link',
    'signin_with_facebook' => 'Login with Facebook',
    'signin_with_google' => 'Login with Google',
    'signin_with_apple' => 'Login with Apple',
    'enter_mobile_number' => 'Please enter your mobile number',
    'request_otp' => 'Request OTP',
    'resend_otp' => 'Resend OTP',
    'verify_now' => 'Verify Now',
    'referral_code_placeholder' => 'Referral Code (Optional)',
  ),
)
                ;