<?php

                return array (
  'pagination' => 
  array (
    'show' => 'Show',
    'page' => 'Page',
  ),
  'nav_menu' => 
  array (
    'welcome' => 'Welcome!',
    'joined_on' => 'Joined On',
  ),
  'claim' => 
  array (
    'validation_error' => 'Please fill all the details',
    'create_claim' => 'Create Claim',
    'create_claim_btn' => 'Create Claim',
    'store' => 'Store',
    'shopping_trip' => 'Shopping Trip',
    'ordering_platform' => 'Ordering Platform',
    'order_id' => 'Order ID',
    'currency' => 'Currency',
    'amount_placeholder' => 'Amount',
    'date' => 'Date',
    'additional_information' => 'Additional Information',
    'submit_btn' => 'Submit',
    'note' => 'IMPORTANT NOTE:',
    'create_claim_success' => 'Claim created successfully!',
    'claim_request_failed' => 'Claim request failed! Try again',
    'no_claims' => 'No Claims found!',
    'purchase_date' => 'Purchase Date',
    'website' => 'Website',
    'mobile' => 'Mobile',
    'ios' => 'iOS',
    'android' => 'Android',
    'ordering_id' => 'Ordering ID',
    'closed' => 'Claim is closed',
    'receipt' => 'Receipt',
    'max_size_note' => 'Maximum file size allowed :MAXSIZE . Accepted format- jpeg,jpg,png',
    'no_click_note' => 'No shopping trips found in last couple of days to report the missing claim, please check later',
    'show' => 'Show',
  ),
  'favorites' => 
  array (
    'no_favorite_found' => 'No Favorite stores found!',
    'loading' => 'loading...',
    'cashback' => 'Cashback',
    'shop_now' => 'Shop Now',
  ),
  'payment_mode' => 
  array (
    'validation_error' => 'Please fill all the details',
    'name' => 'Name',
    'add' => 'Add',
    'name_placeholder' => 'Your Payment Mode Nickname',
    'payment_mode_success' => 'Payment mode added successfully!',
    'payment_mode_error' => 'Payout mode add request failed',
    'invalid_mode' => 'Invalid Payment Mode',
    'not added' => 'The payment method not added.',
  ),
  'account_setting' => 
  array (
    'edit_profile' => 'Edit Profile',
    'manage_profile' => 'Manage your profile information.',
    'firstname_placeholder' => 'Enter First Name',
    'lastname_placeholder' => 'Enter Last Name',
    'change_password' => 'Change Password',
    'manage_password' => 'Manage Password',
    'current_password' => 'Current Password',
    'current_password_placeholder' => 'Enter Current Password',
    'new_password' => 'New Password',
    'change_password_btn' => 'Change Password',
    'change_email_note' => 'To change your email address please contact us.',
    'resend_btn' => 'Resend',
    'confirm_password_validation' => 'New password and confirm passwords are not matching',
    'form_validation' => 'Enter All Values',
    'firstname' => 'First Name',
    'lastname' => 'Last Name',
    'save_btn' => 'Save',
    'new_password_placeholder' => 'Enter New Password',
    'confirm_password' => 'Confirm Password',
    'confirm_password_placeholder' => 'Enter Confirm Password',
    'email' => 'Email',
    'email_placeholder' => 'Email',
    'link_mobile_number' => 'Link Mobile Number',
    'link_number_note' => 'Contact us to change your mobile number.',
    'bio_placeholder' => 'Bio',
    'bio' => 'Bio',
    'birth_date' => 'Birth Date',
    'anniversary_date' => 'Anniversary Date',
    'gender' => 'Gender',
    'marital_status' => 'Marital Status',
    'occupation' => 'Occupation',
    'occupation_placeholder' => 'Occupation',
    'address' => 'Address',
    'address_placeholder' => 'Address',
    'city' => 'City',
    'city_placeholder' => 'City',
    'state' => 'State',
    'state_placeholder' => 'State',
    'country' => 'Country',
    'pincode' => 'Pincode',
    'pincode_placeholder' => 'Pincode',
    'choose_lang' => 'Choose Language',
    'profile_info_updated' => 'Profile Updated Successfully!',
    'request_failed_try_again' => 'Request failed. Please try again!',
    'lang_updated' => 'Language Updated Successfully!',
    'lang_update_request_failed' => 'Language Update Request Failed',
    'password_change_success' => 'Password Changed Successfully!',
    'change_password_error' => 'Change password request failed! Try again',
    'activation_link_sent' => 'Account activation link sent to your mail, Please check',
    'activation_failed' => 'Account activation failed',
    'name_updated' => 'Name Updated Successfully!',
    'male' => 'Male',
    'female' => 'Female',
    'other' => 'Other',
    'enter_value_alert' => 'Please fill all mandatory fields',
    'married' => 'Married',
    'single' => 'Single',
    'please_select' => 'Please Select',
    'email_verification_note' => 'Email NOT verified. Resend verification email.',
    'wrong_password' => 'Current password value is wrong',
    'invalid_lang' => 'Invalid language',
    'same_password' => 'Current password and New password are similar. Please choose a different password',
  ),
  'share_earn' => 
  array (
    'create_link' => 'Create your own links and earn money when others shop',
    'link_title_note' => 'Enter the meaningful title so that your friend knows the offers details.',
    'offer_link_placeholder' => 'Enter offer link',
    'offer_title_placeholder' => 'Enter offer title',
    'link_note' => 'Enter clear link, no referral and customized links',
    'create_link_btn' => 'Create Link',
    'learn_share_earn' => 'Learn Share & Earn',
    'link_success_msg' => 'Link created successfully. Copy this link & share',
    'share_with' => 'Share With',
    'validation_error' => 'Please fill all the details',
    'offer_title' => 'Offer title',
    'copy_link' => 'Copy Link',
    'or' => 'OR',
    'create_new_link' => 'Create New Link',
    'offer_title_note' => 'Enter the meaningful title so that your friend  knows the offers details.',
    'link_error_msg' => 'Please enter a valid link',
    'network_error' => 'Network Error',
    'copied_link' => 'Copied Link',
    'offer_link' => 'Offer link',
    'how_share_earn_works' => 'How Share & Earn Works',
    'see_terms' => 'See terms',
    'disable_warn' => 'Share & Earn is disabled for your account, please contact us for more information',
  ),
  'refer_earn' => 
  array (
    'invite_friends_reward' => 'for all the transactions your friend makes .',
    'copy_link' => 'Copy Link',
    'referral_link_note' => 'Your unique referral link',
    'invite_by_email' => 'Invite by Email',
    'email_placeholder' => 'Enter multiple email IDs separated by comma.',
    'share_with_social' => 'Share with social media',
    'referral_terms' => 'Referral Terms',
    'referral_activities' => 'Your Referral Activities',
    'email_error' => 'Enter valid email address',
    'see_terms' => 'See Terms',
    'invite_sent' => 'Invite Sent',
    'enter_email_placeholder' => 'Enter Email',
    'invite' => 'Invite',
    'invite_bonus_condition' => '(*The bonus will be tracked as pending, you & your friends need to earn cashback worth :MAXCASHBACK within :REDEEMLIMIT days of joining to be able to get the bonus confirmed, failing which it will expire)',
    'invite_friends_bonus' => 'When any one joins using your referral link, you will earn',
    'join_with_refer' => 'Any friend joins our platform will earn',
    'how_refer_earn_works' => 'How Refer & Earn Works',
    'eligibility_terms' => 'Eligibility Terms',
    'eligibility_terms_first' => 'Referral bonus gets confirmed when confirmed cashback worth :AMOUNT earned within :DAYS days',
    'eligibility_terms_second' => 'Joining bonus gets confirmed when confirmed cashback worth :AMOUNT earned within :DAYS days.',
    'eligibility_terms_third' => 'Your referral bonus gets confirmed only when your referred friend bonus confirms.',
    'eligibility_terms_fourth' => 'The status for the referral earning is directly linked to your friend\'s transactions status.',
    'referral_reward' => 'Referral Reward',
    'referral_bonus' => 'Referral Bonus',
    'joining_bonus' => 'Joining Bonus',
    'disable_warn' => 'Refer & Earn is disabled for your account, please contact us for more information',
  ),
  'activities' => 
  array (
    'shopping_tab' => 'Shopping',
    'referral_tab' => 'Referral',
    'bonus_tab' => 'Bonus',
    'click_tab' => 'Clicks',
  ),
  'payment' => 
  array (
    'payments_tab' => 'Payments',
    'history_tab' => 'History',
    'amount_validation_alert' => 'Amount should be more than minimum payable amount',
    'available_for_payment' => 'Available For Payment',
    'payment_mode' => 'Your Payment Mode',
    'minimum_payout' => 'Minimum Payout',
    'available_payout' => 'Available Payout',
    'add_payment_mode' => 'Add New Payment Mode',
    'not_enough_amount' => 'Not enough amount',
    'cashback' => 'Cashback',
    'reward' => 'Reward',
    'request_payout' => 'Request Payout',
    'payout_request_success' => 'Payout requested successfully',
    'payout_request_error' => 'Payout request failed! Try again',
    'pending_payment' => 'Your previous request is in process, please raise a new request later.',
    'not_found' => 'Payment Request not found',
    'already_verified' => 'The request is already verified',
    'success_verified' => 'Payment Request is successfully verified',
    'email_sent' => 'Email Sent Successfully!',
    'email_request_failed' => 'Email request failed',
    'enter_amount' => 'Enter Amount in USD',
    'enter_valid_amount' => 'Please enter valid amount. Decimal value is not accepted',
    'previous_request_in_process' => 'Your previous request is in process, please raise a new request later.',
    'account' => 'Account',
    'bitcoin' => 'Bitcoin',
    'rewards-bunny' => 'RewardsBunny',
    'ethereum' => 'Ethereum',
    'USD' => 'USD',
    'total_paid' => 'Total Paid',
    'there_is_no_paid_amount' => 'There is no paid amount as of now.',
    'pax-gold' => 'Pax Gold',
  ),
  'overview' => 
  array (
    'total_earned' => 'Total Earned',
    'available' => 'Available',
    'paid' => 'Paid',
    'pending' => 'Pending',
  ),
  'common' => 
  array (
    'cashback' => 'Cashback',
    'reward' => 'Reward',
    'already_verified' => 'Already Verified?',
    'email_not_verified' => 'Your email is not verified yet, please activate',
    'verify_alert' => 'Please verify your email to fully access your account.',
    'request_verification' => 'Request new verification if email not received.',
    'resend_verification_btn' => 'Resend Verification Email',
    'click_here' => 'Click Here',
    'cashback_reward_earning' => 'Cashback & Reward Earning',
    'month_wise_earning' => 'View month wise cashback & bonus earning',
    'shopping_trips' => 'Shopping Trips',
    'view_daily_clicks' => 'View daily clicks for last :DAYS days',
    'up_to' => 'Up to',
    'flat' => 'Flat',
    'are_you_sure' => 'Are you sure?',
    'yes' => 'Yes',
    'no' => 'No',
  ),
  'search_filter' => 
  array (
    'popular' => 'Popular',
    'alphabetical' => 'Alphabetical',
    'cashback' => 'Cashback',
    'search_records' => 'Search :COUNT records',
    'search_record_placeholder' => 'Search records',
  ),
)
                ;