<?php

                return array (
  'attributes' => 
  array (
    'email' => '',
    'g-recaptcha-response' => '',
    'privacy policy' => '',
    'referrer_code' => '',
    'password' => '',
    'phone' => '',
    'store_id' => '',
    'click_id' => '',
    'platform' => '',
    'order_amount' => '',
    'currency' => '',
    'transaction_date' => '',
    'user_message' => '',
    'comment' => '',
    'mode' => '',
    'method_name' => '',
    'account' => '',
    'pay_mode' => '',
    'payment_amount' => '',
    'old_password' => '',
    'new_password' => '',
    'repeat_password' => '',
    'name' => '',
    'message' => '',
    'reason' => '',
    'first_name' => '',
    'last_name' => '',
    'otp' => '',
    'phone_number' => '',
    'order_id' => '',
  ),
  'size' => 
  array (
    'numeric' => '',
    'file' => '',
    'string' => '',
    'array' => '',
  ),
  'min' => 
  array (
    'numeric' => '',
    'file' => '',
    'string' => '',
    'array' => '',
  ),
  'max' => 
  array (
    'numeric' => '',
    'file' => '',
    'string' => '',
    'array' => '',
  ),
  'lte' => 
  array (
    'numeric' => '',
    'file' => '',
    'string' => '',
    'array' => '',
  ),
  'lt' => 
  array (
    'numeric' => '',
    'file' => '',
    'string' => '',
    'array' => '',
  ),
  'gte' => 
  array (
    'numeric' => '',
    'file' => '',
    'string' => '',
    'array' => '',
  ),
  'gt' => 
  array (
    'numeric' => '',
    'file' => '',
    'string' => '',
    'array' => '',
  ),
  'between' => 
  array (
    'numeric' => '',
    'file' => '',
    'string' => '',
    'array' => '',
  ),
  'accepted' => '',
  'active_url' => '',
  'after' => '',
  'after_or_equal' => '',
  'alpha' => '',
  'alpha_dash' => '',
  'alpha_num' => '',
  'array' => '',
  'before' => '',
  'before_or_equal' => '',
  'boolean' => '',
  'confirmed' => '',
  'date' => '',
  'date_equals' => '',
  'date_format' => '',
  'different' => '',
  'digits' => '',
  'digits_between' => '',
  'dimensions' => '',
  'distinct' => '',
  'email' => '',
  'ends_with' => '',
  'exists' => '',
  'file' => '',
  'filled' => '',
  'image' => '',
  'in' => '',
  'in-array' => '',
  'integer' => '',
  'ip' => '',
  'ipv4' => '',
  'ipv6' => '',
  'json' => '',
  'mimes' => '',
  'mimetypes' => '',
  'not_in' => '',
  'not_regex' => '',
  'numeric' => '',
  'password' => '',
  'present' => '',
  'regex' => '',
  'required' => '',
  'required_if' => '',
  'required_unless' => '',
  'required_with' => '',
  'required_with_all' => '',
  'required_without' => '',
  'required_without_all' => '',
  'same' => '',
  'string' => '',
  'timezone' => '',
  'unique' => '',
  'uploaded' => '',
  'url' => '',
  'uuid' => '',
  'email_not_exist' => '',
  'not_registerd_using_email' => '',
  'phone_number_exist' => '',
)
                ;