<?php

                return array (
  'verify' => 
  array (
    'title' => 'अपने खाते को सत्यापित करें',
  ),
  'ajax' => 
  array (
    'login_success' => 'आप सफलतापूर्वक लॉग इन हो गए हैं',
    'login_error' => 'ईमेल और / या पासवर्ड अमान्य है।',
    'otp_sent' => 'OTP भेजा गया',
    'otp_send_error' => 'OTP भेजने में असमर्थ, बाद में पुनः प्रयास करें',
    'otp_error' => 'कुछ गलत हो गया',
    'otp_validation' => 'फोन नंबर और ओटीपी आवश्यक है',
    'otp_verify_success' => 'सत्यापित',
    'otp_verify_error' => 'ओटीपी मिसमैच, कृपया जाँच करें और पुनः प्रयास करें',
    'register_success' => 'आपने सफलतापूर्वक पंजीकरण कर लिया है।',
    'forgot_password_success' => 'हमने आपको पासवर्ड रीसेट करने के लिए निर्देश भेजा है, कृपया अपना ईमेल देखें',
    'social_media_login_error' => 'कुछ गलत हो गया!',
    'unable_to_create_account' => 'खाता बनाने में असमर्थ',
    'password_updated' => 'पासवर्ड अपडेट किया गया',
    'otp_invalid' => 'OTP अमान्य है',
    'user_not_exist' => 'उपयोगकर्ता मौजूद नहीं है',
    'user_logged_out' => 'उपयोगकर्ता लॉग आउट हो गया',
    'cross_user_request' => 'उपयोगकर्ता के अनुरोध को पार करें या उपयोगकर्ता लॉग आउट हो',
    'invalid_session' => 'अवैध सत्र',
    'invalid_token' => 'अमान्य टोकन',
    'user_banned' => 'यह उपयोगकर्ता प्रतिबंधित है',
    'invalid_credentials' => 'प्रदान की गई क्रेडेंशियल गलत हैं।',
  ),
  'toast' => 
  array (
    'login_success' => 'आप सफलतापूर्वक लॉग इन हो गए हैं',
    'logout_success' => 'आप लॉग आउट हैं, जल्द ही वापस आएँगे!',
    'verify_info' => 'आपका खाता पहले से ही सत्यापित है।',
    'verify_success' => 'आपने अपने ईमेल को सफलतापूर्वक सत्यापित कर लिया है, अब आपके कैशबैक खाते से प्रतिबंध हटा दिया गया है',
    'register_success' => 'आपने सफलतापूर्वक पंजीकरण कर लिया है।',
    'reset_password_success' => 'आपका पासवर्ड सफलतापूर्वक रीसेट कर दिया गया है।',
    'login_to_proceed' => 'आगे बढ़ने के लिए आपको लॉग इन करना होगा',
  ),
  'failed' => 'ये प्रमाण हमारे रिकॉर्ड से मेल नहीं खाते हैं।',
  'throttle' => 'बहुत सारे लॉगिन प्रयास। कृपया फिर से प्रयास करें: सेकंड सेकंड।',
  'invalid_signature' => 'अमान्य हस्ताक्षर',
  'button' => 
  array (
    'change_password' => 'पासवर्ड बदलें',
    'signin' => 'साइन इन करें',
    'join_now' => 'अब सम्मिलित हों',
    'logout' => 'लॉग आउट',
  ),
  'form' => 
  array (
    'email_placeholder' => 'ईमेल',
    'password_placeholder' => 'पास वर्ड दर्ज करें',
    'existing_user' => 'मौजूदा उपयोगकर्ता',
    'note' => 'हम आपकी अनुमति के बिना कुछ भी पोस्ट नहीं करेंगे।',
    'terms_apply' => 'जॉइनिंग और रेफरल बोनस शर्तें लागू करें *',
    'remember_me' => 'मुझे याद रखना',
    'reset_password' => 'अपना पासवर्ड रीसेट करें',
    'email_valid_msg' => 'अच्छा लग रहा है!',
    'forgot_password_link' => 'पासवर्ड भूल गए ?',
    'forgot_password_note' => 'अपना ईमेल पता दर्ज करें और हम आपको अपना पासवर्ड रीसेट करने के लिए निर्देश भेजेंगे',
    'time_left' => 'समय बचा =',
    'not_member' => 'सदस्य नहीं',
    'sign_up_get' => 'साइन अप करें और प्राप्त करें',
    'today' => 'आज',
    'social_media_signup' => 'स्वागत: मंच, आप हमारी भयानक कैशबैक वेबसाइट में शामिल होने से बस एक क्लिक दूर हैं।',
    'someone_refer_you' => 'क्या किसी ने आपका जिक्र किया?',
    'enter_otp' => 'OTP दर्ज करें',
    'social_media_email_validation' => 'सत्यापन लिंक प्राप्त करने के लिए मान्य ईमेल दर्ज करें',
    'agree_policy' => 'मैं <a href=\':PRIVACY \'वर्ग=\'text-purple\' target=\'_blank\'> गोपनीयता नीति </a> और <a href =\': TERMS की कक्षा = \'पाठ-बैंगनी\' लक्ष्य = \'रिक्त\' से सहमत हूं \'> उपयोग की शर्तें </a>',
    'forgot_password' => 'पासवर्ड भूल गए !',
    'signin' => 'साइन इन करें',
    'send_reset_link' => 'पासवर्ड रीसेट लिंक भेजें',
    'signin_with_facebook' => 'फ़ेसबुक से साइन इन करें',
    'signin_with_google' => 'Google के साथ साइन इन करें',
    'signin_with_apple' => 'Apple के साथ साइन इन करें',
    'enter_mobile_number' => 'अपना मोबाइल नंबर दर्ज करें',
    'request_otp' => 'OTP का अनुरोध करें',
    'resend_otp' => 'ओटीपी पुनः भेजें',
    'verify_now' => 'अभी सत्यापित करें',
    'referral_code_placeholder' => 'रेफरल कोड (वैकल्पिक)',
  ),
)
                ;