<?php

                return array (
  'pagination' => 
  array (
    'show' => 'प्रदर्शन',
    'page' => 'पृष्ठ',
  ),
  'nav_menu' => 
  array (
    'welcome' => 'स्वागत हे',
    'joined_on' => 'पर शामिल हुए',
  ),
  'claim' => 
  array (
    'validation_error' => 'कृपया सभी विवरण भरें',
    'create_claim' => 'मिसिंग कैशबैक क्लेम बनाएं',
    'create_claim_btn' => 'दावा बनाएँ',
    'store' => 'दुकान',
    'shopping_trip' => 'खरीददारी अभियान',
    'ordering_platform' => 'प्लेटफ़ॉर्म ऑर्डर कर रहा है',
    'order_id' => 'आदेश ID',
    'currency' => 'मुद्रा',
    'amount_placeholder' => 'रकम',
    'date' => ':attribute एक वैध तारीख नहीं है।',
    'additional_information' => 'अतिरिक्त जानकारी',
    'submit_btn' => 'प्रस्तुत',
    'note' => 'हम आपकी अनुमति के बिना कुछ भी पोस्ट नहीं करेंगे।',
    'create_claim_success' => 'सफलतापूर्वक बनाया गया दावा!',
    'claim_request_failed' => 'दावा अनुरोध विफल! पुनः प्रयास करें',
    'no_claims' => 'कोई दावा नहीं मिला!',
    'purchase_date' => 'खरीद की तारीख',
    'website' => 'वेबसाइट',
    'mobile' => 'मोबाइल',
    'ios' => 'आईओएस',
    'android' => 'एंड्रॉयड',
    'ordering_id' => 'आदेश देने वाली आई.डी.',
    'closed' => 'दावा बंद है',
  ),
  'favorites' => 
  array (
    'no_favorite_found' => 'कोई पसंदीदा स्टोर नहीं मिला!',
    'loading' => 'लोड हो रहा है...',
    'cashback' => 'नकदी वापस',
    'shop_now' => 'अभी खरीदो',
  ),
  'payment_mode' => 
  array (
    'validation_error' => 'कृपया सभी विवरण भरें',
    'name' => 'नाम',
    'add' => 'जोड़ना',
    'name_placeholder' => 'प्लेसहोल्डर का नाम',
    'payment_mode_success' => 'भुगतान मोड सफलतापूर्वक जोड़ा गया!',
    'payment_mode_error' => 'भुगतान मोड जोड़ने का अनुरोध विफल रहा',
    'invalid_mode' => 'अमान्य भुगतान मोड',
    'not added' => 'भुगतान मोड नहीं जोड़ा गया',
  ),
  'account_setting' => 
  array (
    'edit_profile' => 'प्रोफ़ाइल संपादित करें',
    'manage_profile' => 'अपनी प्रोफ़ाइल जानकारी प्रबंधित करें।',
    'firstname_placeholder' => 'पहला नाम दर्ज करें',
    'lastname_placeholder' => 'अंतिम नाम दर्ज करो',
    'change_password' => 'पासवर्ड बदलें',
    'manage_password' => 'पासवर्ड प्रबंधित करें',
    'current_password' => 'वर्तमान पासवर्ड',
    'current_password_placeholder' => 'वर्तमान पासवर्ड डालें',
    'new_password' => 'नया पासवर्ड',
    'change_password_btn' => 'पासवर्ड बदलें',
    'change_email_note' => 'अपना ईमेल बदलने के लिए कृपया हमसे संपर्क करें।',
    'resend_btn' => 'पुन: भेजें',
    'confirm_password_validation' => 'नया पासवर्ड और पुष्टिकरण पासवर्ड मेल नहीं खा रहे हैं',
    'form_validation' => 'सभी मान दर्ज करें',
    'firstname' => 'पहला नाम',
    'lastname' => 'अंतिम नाम',
    'save_btn' => 'सहेजें',
    'new_password_placeholder' => 'नया पासवर्ड दर्ज करें',
    'confirm_password' => 'पासवर्ड की पुष्टि कीजिये',
    'confirm_password_placeholder' => 'पासवर्ड की पुष्टि करें',
    'email' => 'ईमेल',
    'email_placeholder' => 'ईमेल',
    'link_mobile_number' => 'मोबाइल नंबर लिंक करें',
    'link_number_note' => 'अपना मोबाइल नंबर बदलने के लिए हमसे संपर्क करें।',
    'bio_placeholder' => 'जैव',
    'bio' => 'जैव',
    'birth_date' => 'जन्म दिन',
    'anniversary_date' => 'सालगिरह की तिथि',
    'gender' => 'लिंग',
    'marital_status' => 'वैवाहिक स्थिति',
    'occupation' => 'व्यवसाय',
    'occupation_placeholder' => 'व्यवसाय',
    'address' => '',
    'address_placeholder' => 'पता',
    'city' => 'शहर',
    'city_placeholder' => 'शहर',
    'state' => 'राज्य',
    'state_placeholder' => 'राज्य',
    'country' => 'देश',
    'pincode' => 'पिन कोड',
    'pincode_placeholder' => 'पिन कोड',
    'choose_lang' => 'भाषा चुनें',
    'profile_info_updated' => 'प्रोफाइल को सफलतापूर्वक अपडेट किया गया!',
    'request_failed_try_again' => 'अनुरोध फिर से विफल रहा',
    'lang_updated' => 'भाषा अद्यतन सफलतापूर्वक!',
    'lang_update_request_failed' => 'भाषा अद्यतन अनुरोध विफल',
    'password_change_success' => 'पासवर्ड सफलतापूर्वक बदला गया !',
    'change_password_error' => 'पासवर्ड बदलने का अनुरोध विफल! पुनः प्रयास करें',
    'activation_link_sent' => 'खाता सक्रियण लिंक आपके मेल पर भेजा गया है, कृपया देखें',
    'activation_failed' => 'खाता सक्रियण विफल रहा',
    'name_updated' => 'नाम अद्यतन सफलतापूर्वक!',
    'male' => 'पुरुष',
    'female' => 'महिला',
    'other' => 'Other',
    'enter_value_alert' => 'कृपया सभी अनिवार्य फ़ील्ड भरें',
    'married' => 'विवाहित',
    'single' => 'एक',
    'please_select' => 'कृपया चुने',
    'email_verification_note' => 'ईमेल सत्यापित नहीं है। सत्यापन ईमेल पुनः भेजे।',
    'wrong_password' => 'वर्तमान पासवर्ड मान गलत है',
    'invalid_lang' => 'अमान्य लैंग',
    'same_password' => '',
  ),
  'share_earn' => 
  array (
    'create_link' => 'अपनी खुद की लिंक बनाएं और दूसरों की दुकान पर पैसा कमाएं',
    'link_title_note' => 'सार्थक शीर्षक दर्ज करें ताकि आपके मित्र को विवरण की जानकारी हो।',
    'offer_link_placeholder' => 'ऑफर लिंक दर्ज करें',
    'offer_title_placeholder' => 'ऑफर शीर्षक दर्ज करें',
    'link_note' => 'स्पष्ट लिंक, कोई रेफरल और अनुकूलित लिंक दर्ज करें',
    'create_link_btn' => 'लिंक बनाएं',
    'learn_share_earn' => 'शेयर और कमाएँ सीखें',
    'link_success_msg' => 'लिंक सफलतापूर्वक बनाया गया। इस लिंक को कॉपी करें और शेयर करें',
    'share_with' => 'के साथ शेयर करें',
    'validation_error' => 'कृपया सभी विवरण भरें',
    'offer_title' => 'शीर्षक प्रदान करें',
    'copy_link' => 'प्रतिरूप जोड़ना',
    'or' => 'या',
    'create_new_link' => 'नया लिंक बनाएं',
    'offer_title_note' => 'सार्थक शीर्षक दर्ज करें ताकि आपके मित्र को विवरण की जानकारी हो।',
    'link_error_msg' => 'कृपया मान्य लिंक url डालें',
    'network_error' => 'नेटवर्क त्रुटि',
    'copied_link' => 'नकल की कड़ी',
    'offer_link' => 'लिंक की पेशकश करें',
  ),
  'refer_earn' => 
  array (
    'invite_bonus_msg' => 'दोस्तों को आमंत्रित करें और :BONUS% बोनस प्राप्त करें!',
    'copy_link' => 'प्रतिरूप जोड़ना',
    'referral_link_note' => 'आपका अद्वितीय रेफरल लिंक।',
    'invite_by_email' => 'ईमेल द्वारा आमंत्रित करें',
    'email_placeholder' => 'अल्पविराम द्वारा अलग किए गए कई ईमेल आईडी दर्ज करें।',
    'share_with_social' => 'सोशल मीडिया के साथ साझा करें',
    'referral_terms' => 'रेफरल शर्तें',
    'referral_activities' => 'आपकी रेफरल गतिविधियाँ',
    'email_error' => 'मान्य ईमेल मान दर्ज करें',
    'see_terms' => 'शर्तें देखें',
    'invite_sent' => 'आमंत्रण भेज दिया',
    'enter_email_placeholder' => 'ईमेल दर्ज करें',
    'invite' => 'आमंत्रण',
  ),
  'activities' => 
  array (
    'shopping_tab' => 'खरीदारी',
    'referral_tab' => 'रेफरल',
    'bonus_tab' => 'बक्शीश',
    'click_tab' => 'क्लिक्स',
  ),
  'payment' => 
  array (
    'payments_tab' => 'भुगतान',
    'history_tab' => 'इतिहास',
    'amount_validation_alert' => 'राशि न्यूनतम देय राशि से अधिक होनी चाहिए',
    'available_for_payment' => 'भुगतान के लिए उपलब्ध है',
    'payment_mode' => 'आपका भुगतान मोड',
    'minimum_payout' => 'न्यूनतम भुगतान',
    'available_payout' => 'उपलब्ध भुगतान',
    'add_payment_mode' => 'नया भुगतान मोड जोड़ें',
    'not_enough_amount' => 'पर्याप्त राशि नहीं है',
    'cashback' => 'नकदी वापस',
    'reward' => 'इनाम',
    'request_payout' => 'भुगतान अनुरोध',
    'payout_request_success' => 'भुगतान अनुरोध को सत्यापित करने के लिए कृपया अपना ईमेल देखें।',
    'payout_request_error' => 'भुगतान अनुरोध विफल हुआ! पुन: प्रयास करें',
    'pending_payment' => 'आपका पिछला अनुरोध प्रक्रिया में है, कृपया बाद में नया अनुरोध बढ़ाएँ।',
    'not_found' => 'भुगतान अनुरोध नहीं मिला',
    'already_verified' => 'भुगतान अनुरोध पहले से सत्यापित है',
    'success_verified' => 'भुगतान अनुरोध सफलतापूर्वक सत्यापित है',
    'email_sent' => 'सफलतापूर्वक भेजा गया ईमेल !',
    'email_request_failed' => 'ईमेल अनुरोध विफल रहा',
    'enter_amount' => 'राशी डालें',
    'enter_valid_amount' => 'कृपया मान्य राशि दर्ज करें। दशमलव मान स्वीकार नहीं किया जाता है',
    'previous_request_in_process' => 'आपका पिछला अनुरोध प्रक्रिया में है, कृपया बाद में नया अनुरोध बढ़ाएँ।',
  ),
  'overview' => 
  array (
    'total_earned' => 'कुल कमाई',
    'available' => 'उपलब्ध',
    'paid' => 'भुगतान किया है',
    'pending' => 'विचाराधीन',
  ),
  'common' => 
  array (
    'cashback' => 'नकदी वापस',
    'reward' => 'इनाम',
    'already_verified' => 'पहले से ही सत्यापित?',
    'email_not_verified' => 'आपका ईमेल अभी तक सत्यापित नहीं है, कृपया सक्रिय करें',
    'verify_alert' => 'कृपया अपने कैशबैक खाते तक पूरी तरह से पहुंचने के लिए अपने ईमेल को सत्यापित करें।',
    'request_verification' => 'ईमेल न मिलने पर नए सत्यापन का अनुरोध करें।',
    'resend_verification_btn' => 'सत्यापन ईमेल पुनः भेजे',
    'click_here' => 'यहाँ क्लिक करें',
    'cashback_reward_earning' => 'कैशबैक और रिवार्ड अर्निंग',
    'month_wise_earning' => 'महीनेवार कैशबैक और बोनस कमाई देखें',
    'shopping_trips' => 'खरीदारी यात्राएं',
    'view_daily_clicks' => 'पिछले :DAYS दिनों के लिए दैनिक क्लिक देखें',
    'up_to' => 'तक',
    'flat' => 'समतल',
    'are_you_sure' => 'क्या आपको यकीन है?',
    'yes' => 'हाँ',
    'no' => 'नहीं',
  ),
  'search_filter' => 
  array (
    'popular' => 'लोकप्रिय',
    'alphabetical' => 'वर्णमाला',
    'cashback' => 'नकदी वापस',
    'search_records' => ':COUNT रिकॉर्ड खोजें ...',
    'search_record_placeholder' => 'रिकॉर्ड खोजें',
  ),
)
                ;