<?php

                return array (
  'attributes' => 
  array (
    'email' => 'ईमेल',
    'g-recaptcha-response' => 'जी-आवर्ती-प्रतिक्रिया',
    'privacy policy' => 'गोपनीयता नीति',
    'referrer_code' => 'संदर्भ कोड',
    'password' => 'कुंजिका',
    'phone' => 'फ़ोन',
    'store_id' => 'दुकान',
    'click_id' => 'क्लिक',
    'platform' => 'मंच',
    'order_amount' => 'ऑर्डर करने की राशि',
    'currency' => 'मुद्रा',
    'transaction_date' => 'लेन - देन की तारीख',
    'user_message' => 'उपयोगकर्ता संदेश',
    'comment' => 'टिप्पणी',
    'mode' => 'मोड',
    'method_name' => 'विधि का नाम',
    'account' => 'लेखा',
    'pay_mode' => 'भुगतान का प्रकार',
    'payment_amount' => 'भुगतान राशि',
    'old_password' => 'पुराना पासवर्ड',
    'new_password' => 'नया पासवर्ड',
    'repeat_password' => 'पासवर्ड दोहराएं',
    'name' => 'नाम',
    'message' => 'संदेश',
    'reason' => 'कारण',
    'first_name' => 'ईमेल',
    'last_name' => 'ईमेल',
    'otp' => 'ईमेल',
    'phone_number' => 'ईमेल',
    'order_id' => 'आदेश ID',
  ),
  'size' => 
  array (
    'numeric' => ':attribute :size होना चाहिए।',
    'file' => ':attribute :size किलोबाइट होना चाहिए।',
    'string' => ':attribute में :size अक्षर होने चाहिए।',
    'array' => ':attribute में :size आइटम होना चाहिए।',
  ),
  'min' => 
  array (
    'numeric' => ':attribute कम से कम :min होना चाहिए।',
    'file' => ':attribute कम से कम :min किलोबाइट होना चाहिए।',
    'string' => ':attribute में कम से कम :min अक्षर होने चाहिए।',
    'array' => ':attribute में कम से कम :min आइटम होना चाहिए।',
  ),
  'max' => 
  array (
    'numeric' => ':attribute :max से अधिक नहीं हो सकता है।',
    'file' => ':attribute :max किलोबाइट से अधिक नहीं हो सकता है।',
    'string' => ':attribute :max वर्णों से अधिक नहीं हो सकता है।',
    'array' => ':attribute में :max से अधिक आइटम नहीं हो सकते हैं।',
  ),
  'lte' => 
  array (
    'numeric' => ':attribute :value से कम या बराबर होना चाहिए।',
    'file' => ':attribute :value किलोबाइट से कम या बराबर होना चाहिए।',
    'string' => ':attribute :value वर्णों से कम या बराबर होना चाहिए।',
    'array' => ':attribute में :value आइटम से अधिक नहीं होना चाहिए।',
  ),
  'lt' => 
  array (
    'numeric' => ':attribute :value से कम होना चाहिए।',
    'file' => ':attribute :value किलोबाइट से कम होना चाहिए।',
    'string' => ':attribute :value वर्णों से कम होना चाहिए।',
    'array' => ':attribute में :value आइटम से कम होना चाहिए।',
  ),
  'gte' => 
  array (
    'numeric' => ':attribute :value से अधिक या बराबर होना चाहिए।',
    'file' => ':attribute :value किलोबाइट से अधिक या बराबर होना चाहिए।',
    'string' => ':attribute वर्ण :value से अधिक या बराबर होना चाहिए।',
    'array' => ':attribute में :value आइटम या अधिक होना चाहिए।',
  ),
  'gt' => 
  array (
    'numeric' => ':attribute :value से अधिक होना चाहिए।',
    'file' => ':attribute :value किलोबाइट से अधिक होना चाहिए।',
    'string' => ':attribute वर्ण :value से अधिक होना चाहिए।',
    'array' => ':attribute में :value आइटम से अधिक होना चाहिए',
  ),
  'between' => 
  array (
    'numeric' => ':attribute :min और :max के बीच होना चाहिए।',
    'file' => ':attribute :min और :max किलोबाइट के बीच होना चाहिए।',
    'string' => ':attribute :min और :max वर्णों के बीच होना चाहिए।',
    'array' => ':attribute को :min और :max आइटम के बीच होना चाहिए।',
  ),
  'accepted' => ':attribute को स्वीकार करना होगा।',
  'active_url' => ':attribute एक मान्य URL नहीं है।',
  'after' => ':attribute के बाद :attribute की तारीख होनी चाहिए।',
  'after_or_equal' => ':attribute के बाद या :date के बराबर तारीख होनी चाहिए।',
  'alpha' => ':attribute में केवल अक्षर हो सकते हैं।',
  'alpha_dash' => ':attribute में केवल अक्षर, संख्या, डैश और अंडरस्कोर हो सकते हैं।',
  'alpha_num' => ':attribute में केवल अक्षर और संख्याएँ हो सकती हैं।',
  'array' => ':attribute एक सरणी होना चाहिए।',
  'before' => ':attribute :date से पहले की तारीख होनी चाहिए।',
  'before_or_equal' => ':attribute :date से पहले या उसके बराबर की तारीख होनी चाहिए।',
  'boolean' => ':attribute फ़ील्ड सही या गलत होना चाहिए।',
  'confirmed' => ':attribute पुष्टिकरण मेल नहीं खाता है।',
  'date' => ':attribute एक वैध तारीख नहीं है।',
  'date_equals' => ':attribute :date के बराबर की तारीख होनी चाहिए।',
  'date_format' => ':attribute प्रारूप :format से मेल नहीं खाता है।',
  'different' => ':attribute और :other अलग-अलग होने चाहिए।',
  'digits' => ':attribute का :digits अंक होना चाहिए।',
  'digits_between' => ':attribute :min और :max अंकों के बीच होना चाहिए।',
  'dimensions' => ':attribute में अमान्य छवि आयाम हैं।',
  'distinct' => ':attribute फ़ील्ड का डुप्लिकेट मान है।',
  'email' => ':attribute एक वैध ईमेल पता होना चाहिए।',
  'ends_with' => ':attribute को निम्नलिखित में से एक के साथ समाप्त होना चाहिए: :values।',
  'exists' => 'चयनित :attribute अमान्य है।',
  'file' => ':attribute फ़ील्ड का डुप्लिकेट मान है।',
  'filled' => ':attribute फ़ील्ड का मान होना चाहिए।',
  'image' => ':attribute एक छवि होनी चाहिए।',
  'in' => 'चयनित :attribute अमान्य है।',
  'in-array' => ':attribute फ़ील्ड :other में मौजूद नहीं है।',
  'integer' => ':attribute पूर्णांक होना चाहिए।',
  'ip' => ':attribute एक मान्य IP पता होना चाहिए।',
  'ipv4' => ':attribute एक मान्य IPv4 पता होना चाहिए।',
  'ipv6' => ':attribute एक मान्य IPv6 पता होना चाहिए।',
  'json' => ':attribute एक वैध JSON स्ट्रिंग होना चाहिए।',
  'mimes' => ':attribute एक प्रकार की फ़ाइल होनी चाहिए: :values।',
  'mimetypes' => ':attribute एक प्रकार की फ़ाइल होनी चाहिए: :values।',
  'not_in' => 'चयनित :attribute अमान्य है।',
  'not_regex' => ':attribute प्रारूप अमान्य है।',
  'numeric' => ':attribute एक नंबर होना चाहिए।',
  'password' => 'पासवर्ड गलत है।',
  'present' => ':attribute फ़ील्ड मौजूद होना चाहिए।',
  'regex' => ':attribute प्रारूप अमान्य है।',
  'required' => ':attribute फ़ील्ड आवश्यक है।',
  'required_if' => ':attribute :value होने पर :attribute फ़ील्ड आवश्यक है।',
  'required_unless' => ':attribute फ़ील्ड आवश्यक है जब तक :other :values में न हो।',
  'required_with' => ':attribute फ़ील्ड आवश्यक है जब :values मौजूद है।',
  'required_with_all' => ':attribute फ़ील्ड आवश्यक है जब :values मौजूद हैं।',
  'required_without' => 'जब :values मौजूद नहीं है, तो :attribute फ़ील्ड आवश्यक है।',
  'required_without_all' => ':attribute फ़ील्ड आवश्यक है जब :values में से कोई भी मौजूद नहीं है।',
  'same' => ':attribute और :other का मिलान होना चाहिए।',
  'string' => ':attribute एक स्ट्रिंग होना चाहिए।',
  'timezone' => ':attribute एक वैध क्षेत्र होना चाहिए।',
  'unique' => ':attribute को पहले ही ले लिया गया है।',
  'uploaded' => ':attribute अपलोड करने में विफल रहा।',
  'url' => ':attribute प्रारूप अमान्य है।',
  'uuid' => ':attribute एक वैध यूयूआईडी होना चाहिए।',
  'email_not_exist' => 'Email does not exist',
  'not_registerd_using_email' => 'आप पासवर्ड रीसेट नहीं कर सकते क्योंकि आपने ईमेल का उपयोग करके पंजीकरण नहीं किया है',
  'phone_number_exist' => 'फ़ोन नंबर पहले से मौजूद है',
)
                ;