<?php

                return array (
  'pagination' => 
  array (
    'show' => '',
    'page' => '',
  ),
  'nav_menu' => 
  array (
    'welcome' => '',
    'joined_on' => '',
  ),
  'claim' => 
  array (
    'validation_error' => '',
    'create_claim' => '',
    'create_claim_btn' => '',
    'store' => '',
    'shopping_trip' => '',
    'ordering_platform' => '',
    'order_id' => '',
    'currency' => '',
    'amount_placeholder' => '',
    'date' => '',
    'additional_information' => '',
    'submit_btn' => '',
    'note' => '',
    'create_claim_success' => '',
    'claim_request_failed' => '',
    'no_claims' => '',
    'purchase_date' => '',
    'website' => '',
    'mobile' => '',
    'ios' => '',
    'android' => '',
    'ordering_id' => '',
    'closed' => '',
  ),
  'favorites' => 
  array (
    'no_favorite_found' => '',
    'loading' => '',
    'cashback' => '',
    'shop_now' => '',
  ),
  'payment_mode' => 
  array (
    'validation_error' => '',
    'name' => '',
    'add' => '',
    'name_placeholder' => '',
    'payment_mode_success' => '',
    'payment_mode_error' => '',
    'invalid_mode' => '',
    'not added' => '',
  ),
  'account_setting' => 
  array (
    'edit_profile' => '',
    'manage_profile' => '',
    'firstname_placeholder' => '',
    'lastname_placeholder' => '',
    'change_password' => '',
    'manage_password' => '',
    'current_password' => '',
    'current_password_placeholder' => '',
    'new_password' => '',
    'change_password_btn' => '',
    'change_email_note' => '',
    'resend_btn' => '',
    'confirm_password_validation' => '',
    'form_validation' => '',
    'firstname' => '',
    'lastname' => '',
    'save_btn' => '',
    'new_password_placeholder' => '',
    'confirm_password' => '',
    'confirm_password_placeholder' => '',
    'email' => '',
    'email_placeholder' => '',
    'link_mobile_number' => '',
    'link_number_note' => '',
    'bio_placeholder' => '',
    'bio' => '',
    'birth_date' => '',
    'anniversary_date' => '',
    'gender' => '',
    'marital_status' => '',
    'occupation' => '',
    'occupation_placeholder' => '',
    'address' => '',
    'address_placeholder' => '',
    'city' => '',
    'city_placeholder' => '',
    'state' => '',
    'state_placeholder' => '',
    'country' => '',
    'pincode' => '',
    'pincode_placeholder' => '',
    'choose_lang' => '',
    'profile_info_updated' => '',
    'request_failed_try_again' => '',
    'lang_updated' => '',
    'lang_update_request_failed' => '',
    'password_change_success' => '',
    'change_password_error' => '',
    'activation_link_sent' => '',
    'activation_failed' => '',
    'name_updated' => '',
    'male' => '',
    'female' => '',
    'other' => '',
    'enter_value_alert' => '',
    'married' => '',
    'single' => '',
    'please_select' => '',
    'email_verification_note' => '',
    'wrong_password' => '',
    'invalid_lang' => '',
    'same_password' => '',
  ),
  'share_earn' => 
  array (
    'create_link' => '',
    'link_title_note' => '',
    'offer_link_placeholder' => '',
    'offer_title_placeholder' => '',
    'link_note' => '',
    'create_link_btn' => '',
    'learn_share_earn' => '',
    'link_success_msg' => '',
    'share_with' => '',
    'validation_error' => '',
    'offer_title' => '',
    'copy_link' => '',
    'or' => '',
    'create_new_link' => '',
    'offer_title_note' => '',
    'link_error_msg' => '',
    'network_error' => '',
    'copied_link' => '',
    'offer_link' => '',
  ),
  'refer_earn' => 
  array (
    'invite_bonus_msg' => '',
    'copy_link' => '',
    'referral_link_note' => '',
    'invite_by_email' => '',
    'email_placeholder' => '',
    'share_with_social' => '',
    'referral_terms' => '',
    'referral_activities' => '',
    'email_error' => '',
    'see_terms' => '',
    'invite_sent' => '',
    'enter_email_placeholder' => '',
    'invite' => '',
  ),
  'activities' => 
  array (
    'shopping_tab' => '',
    'referral_tab' => '',
    'bonus_tab' => '',
    'click_tab' => '',
  ),
  'payment' => 
  array (
    'payments_tab' => '',
    'history_tab' => '',
    'amount_validation_alert' => '',
    'available_for_payment' => '',
    'payment_mode' => '',
    'minimum_payout' => '',
    'available_payout' => '',
    'add_payment_mode' => '',
    'not_enough_amount' => '',
    'cashback' => '',
    'reward' => '',
    'request_payout' => '',
    'payout_request_success' => '',
    'payout_request_error' => '',
    'pending_payment' => '',
    'not_found' => '',
    'already_verified' => '',
    'success_verified' => '',
    'email_sent' => '',
    'email_request_failed' => '',
    'enter_amount' => '',
    'enter_valid_amount' => '',
    'previous_request_in_process' => '',
  ),
  'overview' => 
  array (
    'total_earned' => '',
    'available' => '',
    'paid' => '',
    'pending' => '',
  ),
  'common' => 
  array (
    'cashback' => '',
    'reward' => '',
    'already_verified' => '',
    'email_not_verified' => '',
    'verify_alert' => '',
    'request_verification' => '',
    'resend_verification_btn' => '',
    'click_here' => '',
    'cashback_reward_earning' => '',
    'month_wise_earning' => '',
    'shopping_trips' => '',
    'view_daily_clicks' => '',
    'up_to' => '',
    'flat' => '',
    'are_you_sure' => '',
    'yes' => '',
    'no' => '',
  ),
  'search_filter' => 
  array (
    'popular' => '',
    'alphabetical' => '',
    'cashback' => '',
    'search_records' => '',
    'search_record_placeholder' => '',
  ),
)
                ;