<?php

                return array (
  'verify' => 
  array (
    'title' => '',
  ),
  'ajax' => 
  array (
    'login_success' => '',
    'login_error' => '',
    'otp_sent' => '',
    'otp_send_error' => '',
    'otp_error' => '',
    'otp_validation' => '',
    'otp_verify_success' => '',
    'otp_verify_error' => '',
    'register_success' => '',
    'forgot_password_success' => '',
    'social_media_login_error' => '',
    'unable_to_create_account' => '',
    'password_updated' => '',
    'otp_invalid' => '',
    'user_not_exist' => '',
    'user_logged_out' => '',
    'cross_user_request' => '',
    'invalid_session' => '',
    'invalid_token' => '',
    'user_banned' => '',
    'invalid_credentials' => '',
  ),
  'toast' => 
  array (
    'login_success' => '',
    'logout_success' => '',
    'verify_info' => '',
    'verify_success' => '',
    'register_success' => '',
    'reset_password_success' => '',
    'login_to_proceed' => '',
  ),
  'failed' => '',
  'throttle' => '',
  'invalid_signature' => '',
  'button' => 
  array (
    'change_password' => '',
    'signin' => '',
    'join_now' => '',
    'logout' => '',
  ),
  'form' => 
  array (
    'email_placeholder' => '',
    'password_placeholder' => '',
    'existing_user' => '',
    'note' => '',
    'terms_apply' => '',
    'remember_me' => '',
    'reset_password' => '',
    'email_valid_msg' => '',
    'forgot_password_link' => '',
    'forgot_password_note' => '',
    'time_left' => '',
    'not_member' => '',
    'sign_up_get' => '',
    'today' => '',
    'social_media_signup' => '',
    'someone_refer_you' => '',
    'enter_otp' => '',
    'social_media_email_validation' => '',
    'agree_policy' => '',
    'forgot_password' => '',
    'signin' => '',
    'send_reset_link' => '',
    'signin_with_facebook' => '',
    'signin_with_google' => '',
    'signin_with_apple' => '',
    'enter_mobile_number' => '',
    'request_otp' => '',
    'resend_otp' => '',
    'verify_now' => '',
    'referral_code_placeholder' => '',
  ),
)
                ;