<?php

                return array (
  'verify' => 
  array (
    'title' => 'アカウントを確認する',
  ),
  'ajax' => 
  array (
    'login_success' => '正常にログインしています',
    'login_error' => 'メールアドレスやパスワードが無効です。',
    'otp_sent' => 'OTP送信',
    'otp_send_error' => 'OTPを送信できません。後でもう一度やり直してください',
    'otp_error' => '何かがうまくいかなかった',
    'otp_validation' => '電話番号とOTPが必要です',
    'otp_verify_success' => '確認済み',
    'otp_verify_error' => 'OTPの不一致、確認して再試行してください',
    'register_success' => 'お申し込みいただきありがとうございます。メールで受け取ったリンクをクリックして、メールと携帯電話番号を確認してください。',
    'forgot_password_success' => 'パスワードをリセットする手順をお送りしました。メールを確認してください',
    'social_media_login_error' => '何かがうまくいかなかった！',
    'unable_to_create_account' => 'アカウントを作成できません',
    'password_updated' => 'パスワードが更新されました',
    'otp_invalid' => 'OTPが無効です',
    'user_not_exist' => 'ユーザーは存在しません',
    'user_logged_out' => 'ユーザーがログアウトしました',
    'cross_user_request' => 'クロスユーザーリクエストまたはユーザーがログアウトしました',
    'invalid_session' => '無効なセッション',
    'invalid_token' => '無効なトークン',
    'user_banned' => 'このユーザーは禁止されています',
    'invalid_credentials' => '提供された資格情報が正しくありません。',
  ),
  'toast' => 
  array (
    'login_success' => '正常にログインしています',
    'logout_success' => 'ログアウトしました。すぐに戻ってください。',
    'verify_info' => 'アカウントはすでに確認済みです。',
    'verify_success' => 'メールの確認に成功しました。キャッシュバックアカウントから制限が解除されました',
    'register_success' => 'お申し込みいただきありがとうございます。メールで受け取ったリンクをクリックして、メールと携帯電話番号を確認してください。',
    'reset_password_success' => 'パスワードは正常にリセットされました。',
    'login_to_proceed' => '続行するにはログインする必要があります',
  ),
  'failed' => 'これらの資格情報は、当社の記録と一致しません。',
  'throttle' => 'ログイン試行回数が多すぎます。 :seconds秒後に再試行してください。',
  'invalid_signature' => '無効な署名',
  'button' => 
  array (
    'change_password' => 'パスワードを変更する',
    'signin' => 'ログイン',
    'join_now' => '今すぐ参加',
    'logout' => 'ログアウト',
  ),
  'form' => 
  array (
    'email_placeholder' => 'Eメール',
    'password_placeholder' => 'パスワードを入力する',
    'existing_user' => '既存のユーザー',
    'note' => 'あなたの許可なしに投稿することは決してありません。',
    'terms_apply' => '参加および紹介ボーナス規約が適用されます*',
    'remember_me' => '私を覚えてますか',
    'reset_password' => 'あなたのパスワードをリセット',
    'email_valid_msg' => 'いいね！',
    'forgot_password_link' => 'パスワードをお忘れですか ？',
    'forgot_password_note' => 'メールアドレスを入力してください。パスワードをリセットする手順をお送りします。',
    'time_left' => '残り時間=',
    'not_member' => 'メンバーではありません',
    'sign_up_get' => 'サインアップして入手',
    'today' => '今日',
    'social_media_signup' => 'ようこそ :platform、あなたは私たちの素晴らしいキャッシュバックウェブサイトに参加するためにクリックするだけです。',
    'someone_refer_you' => '誰かがあなたを紹介しましたか？',
    'enter_otp' => 'OTPを入力してください',
    'social_media_email_validation' => '確認リンクを受信するための有効なメールアドレスを入力してください',
    'agree_policy' => '<a href=\':PRIVACY\' class=\'text-purple\'target=\'_blank\'>プライバシーポリシー</a>と<ahref = \'：TERMS\'class =\' text-purple\'target = \'_ blankに同意します\'>利用規約</a>',
    'forgot_password' => 'パスワードをお忘れですか ！',
    'signin' => 'ログイン',
    'send_reset_link' => 'パスワードリセットリンクを送信',
    'signin_with_facebook' => 'Facebookでサインイン',
    'signin_with_google' => 'Googleでサインイン',
    'signin_with_apple' => 'Appleでサインイン',
    'enter_mobile_number' => '携帯電話番号を入力してください',
    'request_otp' => 'OTPをリクエストする',
    'resend_otp' => 'OTPを再送する',
    'verify_now' => '今すぐ確認',
    'referral_code_placeholder' => '紹介コード（オプション）',
  ),
)
                ;