<?php

                return array (
  'pagination' => 
  array (
    'show' => '公演',
    'page' => 'ページ',
  ),
  'nav_menu' => 
  array (
    'welcome' => 'ようこそ',
    'joined_on' => '参加しました',
  ),
  'claim' => 
  array (
    'validation_error' => 'すべての詳細を記入してください',
    'create_claim' => '不足しているキャッシュバック請求を作成する',
    'create_claim_btn' => 'クレームの作成',
    'store' => 'お店',
    'shopping_trip' => '買い物旅行',
    'ordering_platform' => '注文プラットフォーム',
    'order_id' => '注文ID',
    'currency' => '通貨',
    'amount_placeholder' => '量',
    'date' => ':attributeは有効な日付ではありません。',
    'additional_information' => '追加情報',
    'submit_btn' => '参加する',
    'note' => '重要な注意点;',
    'create_claim_success' => 'クレームが正常に作成されました！',
    'claim_request_failed' => 'クレームリクエストに失敗しました！再試行',
    'no_claims' => 'クレームは見つかりませんでした！',
    'purchase_date' => '購入日',
    'website' => 'ウェブサイト',
    'mobile' => 'モバイル',
    'ios' => 'IOS',
    'android' => 'アンドロイド',
    'ordering_id' => '注文ID',
    'closed' => 'クレームはクローズされました',
  ),
  'favorites' => 
  array (
    'no_favorite_found' => 'お気に入りのお店が見つかりません！',
    'loading' => '読み込み中...',
    'cashback' => 'キャッシュバック',
    'shop_now' => '今すぐ購入',
  ),
  'payment_mode' => 
  array (
    'validation_error' => 'すべての詳細を記入してください',
    'name' => '名前',
    'add' => '追加',
    'name_placeholder' => '名前',
    'payment_mode_success' => '支払いモードが正常に追加されました！',
    'payment_mode_error' => '支払いモードの追加リクエストが失敗しました',
    'invalid_mode' => '無効な支払いモード',
    'not added' => '支払いモードは追加されません',
  ),
  'account_setting' => 
  array (
    'edit_profile' => 'プロファイル編集',
    'manage_profile' => 'プロファイル情報を管理します。',
    'firstname_placeholder' => '名を入力してください',
    'lastname_placeholder' => '姓を入力してください',
    'change_password' => 'パスワードを変更する',
    'manage_password' => 'パスワードの管理',
    'current_password' => '現在のパスワード',
    'current_password_placeholder' => '現在のパスワードを入力してください',
    'new_password' => '新しいパスワード',
    'change_password_btn' => 'パスワードを変更する',
    'change_email_note' => 'メールアドレスを変更するには、お問い合わせください。',
    'resend_btn' => '再送',
    'confirm_password_validation' => '新しいパスワードと確認パスワードが一致していません',
    'form_validation' => 'すべての値を入力してください',
    'firstname' => 'ファーストネーム',
    'lastname' => '苗字',
    'save_btn' => 'セーブ',
    'new_password_placeholder' => '新しいパスワードを入力してください',
    'confirm_password' => 'パスワードを認証する',
    'confirm_password_placeholder' => 'パスワードの確認を入力してください',
    'email' => 'Eメール',
    'email_placeholder' => 'Eメール',
    'link_mobile_number' => 'リンク携帯電話番号',
    'link_number_note' => '携帯電話番号を変更するには、お問い合わせください。',
    'bio_placeholder' => 'バイオ',
    'bio' => 'バイオ',
    'birth_date' => '生年月日',
    'anniversary_date' => '記念日',
    'gender' => '性別',
    'marital_status' => '配偶者の有無',
    'occupation' => '職業',
    'occupation_placeholder' => '職業',
    'address' => '',
    'address_placeholder' => '住所',
    'city' => '市',
    'city_placeholder' => '市',
    'state' => '状態',
    'state_placeholder' => '状態',
    'country' => '国',
    'pincode' => 'ピンコード',
    'pincode_placeholder' => 'ピンコード',
    'choose_lang' => '言語を選択',
    'profile_info_updated' => 'プロファイルが正常に更新されました！',
    'request_failed_try_again' => 'リクエストに失敗しました再試行',
    'lang_updated' => '言語が正常に更新されました！',
    'lang_update_request_failed' => '言語更新リクエストが失敗しました',
    'password_change_success' => 'パスワードは正常に変更されました ！',
    'change_password_error' => 'パスワードの変更リクエストに失敗しました！再試行',
    'activation_link_sent' => 'メールに送信されたアカウントアクティベーションリンク、確認してください',
    'activation_failed' => 'アカウントのアクティブ化に失敗しました',
    'name_updated' => '名前が正常に更新されました！',
    'male' => '男性',
    'female' => '女性',
    'other' => 'その他',
    'enter_value_alert' => 'すべての必須フィールドに入力してください',
    'married' => '既婚',
    'single' => 'シングル',
    'please_select' => '選んでください',
    'email_verification_note' => 'メールは確認されていません。確認メールを再送。',
    'wrong_password' => '現在のパスワード値が間違っています',
    'invalid_lang' => '無効な言語',
    'same_password' => '',
  ),
  'share_earn' => 
  array (
    'create_link' => 'あなた自身のリンクを作成し、他の人が買い物をするときにお金を稼ぐ',
    'link_title_note' => '意味のあるタイトルを入力して、友達がオファーの詳細を知るようにします。',
    'offer_link_placeholder' => 'オファーリンクを入力してください',
    'offer_title_placeholder' => 'オファータイトルを入力してください',
    'link_note' => '明確なリンクを入力し、紹介やカスタマイズされたリンクはありません',
    'create_link_btn' => 'リンクを作成する',
    'learn_share_earn' => '共有を学び、稼ぐ',
    'link_success_msg' => 'リンクが正常に作成されました。このリンクをコピーして共有する',
    'share_with' => 'と共有する',
    'validation_error' => 'すべての詳細を記入してください',
    'offer_title' => 'オファータイトル',
    'copy_link' => 'リンクをコピーする',
    'or' => 'または',
    'create_new_link' => '新しいリンクを作成する',
    'offer_title_note' => '意味のあるタイトルを入力して、友だちにオファーの詳細を知らせます。',
    'link_error_msg' => '有効なリンクURLを入力してください',
    'network_error' => 'ネットワークエラー',
    'copied_link' => 'コピーされたリンク',
    'offer_link' => 'オファーリンク',
  ),
  'refer_earn' => 
  array (
    'invite_bonus_msg' => '友達を招待して :BONUS％ボーナスをゲット！',
    'copy_link' => 'リンクをコピーする',
    'referral_link_note' => 'あなたのユニークな紹介リンク。',
    'invite_by_email' => 'メールで招待',
    'email_placeholder' => '複数のメールIDをカンマで区切って入力します。',
    'share_with_social' => 'ソーシャルメディアと共有する',
    'referral_terms' => '紹介条件',
    'referral_activities' => 'あなたの紹介活動',
    'email_error' => '有効なメール値を入力してください',
    'see_terms' => '規約を見る',
    'invite_sent' => '送信済みの招待',
    'enter_email_placeholder' => 'メールアドレスを入力して',
    'invite' => '招待する',
  ),
  'activities' => 
  array (
    'shopping_tab' => 'ショッピング',
    'referral_tab' => '照会',
    'bonus_tab' => 'ボーナス',
    'click_tab' => 'クリック数',
  ),
  'payment' => 
  array (
    'payments_tab' => '支払い',
    'history_tab' => '歴史',
    'amount_validation_alert' => '金額は最低支払額を超える必要があります',
    'available_for_payment' => '支払い可能',
    'payment_mode' => 'お支払いモード',
    'minimum_payout' => '最小支払い',
    'available_payout' => '利用可能な支払い',
    'add_payment_mode' => '新しい支払いモードを追加する',
    'not_enough_amount' => '量が足りない',
    'cashback' => 'キャッシュバック',
    'reward' => '褒賞',
    'request_payout' => '支払いをリクエストする',
    'payout_request_success' => '支払い要求を確認するためにあなたの電子メールをチェックしてください。',
    'payout_request_error' => '支払い要求に失敗しました！再試行してください',
    'pending_payment' => '以前のリクエストは処理中です。後で新しいリクエストを提出してください。',
    'not_found' => '支払い要求が見つかりません',
    'already_verified' => '支払い要求はすでに確認されています',
    'success_verified' => '支払い要求が正常に検証されました',
    'email_sent' => '電子メールを正常に送信 ！',
    'email_request_failed' => 'メールリクエストが失敗しました',
    'enter_amount' => '金額を入力します',
    'enter_valid_amount' => '有効な金額を入力してください。 10進値は受け入れられません',
    'previous_request_in_process' => '以前のリクエストは処理中です。後で新しいリクエストを提出してください。',
  ),
  'overview' => 
  array (
    'total_earned' => '総獲得額',
    'available' => '利用可能',
    'paid' => '有料',
    'pending' => '保留中',
  ),
  'common' => 
  array (
    'cashback' => 'キャッシュバック',
    'reward' => '褒賞',
    'already_verified' => 'すでに確認済みですか？',
    'email_not_verified' => 'メールアドレスはまだ確認されていません。有効にしてください',
    'verify_alert' => 'キャッシュバックアカウントに完全にアクセスするには、メールアドレスを確認してください。',
    'request_verification' => 'メールが届かない場合は、新しい確認をリクエストしてください。',
    'resend_verification_btn' => '確認メールを再送',
    'click_here' => 'ここをクリック',
    'cashback_reward_earning' => 'キャッシュバックと報酬の獲得',
    'month_wise_earning' => '月ごとのキャッシュバックとボーナス獲得を表示',
    'shopping_trips' => 'ショッピング旅行',
    'view_daily_clicks' => '過去 :DAYS日間の毎日のクリック数を表示',
    'up_to' => 'まで',
    'flat' => '平らな',
    'are_you_sure' => '本気ですか？',
    'yes' => 'はい',
    'no' => '番号',
  ),
  'search_filter' => 
  array (
    'popular' => '人気',
    'alphabetical' => 'アルファベット順',
    'cashback' => 'キャッシュバック',
    'search_records' => ':COUNTレコードを検索...',
    'search_record_placeholder' => '検索記録',
  ),
)
                ;