<?php

                return array (
  'attributes' => 
  array (
    'email' => 'Eメール',
    'g-recaptcha-response' => 'g-recaptcha-response',
    'privacy policy' => '個人情報保護方針',
    'referrer_code' => 'リファラーコード',
    'password' => 'パスワード',
    'phone' => '電話',
    'store_id' => 'お店',
    'click_id' => 'クリック',
    'platform' => 'プラットホーム',
    'order_amount' => '注文金額',
    'currency' => '通貨',
    'transaction_date' => '取引日',
    'user_message' => 'ユーザーメッセージ',
    'comment' => 'コメント',
    'mode' => 'モード',
    'method_name' => 'メソッド名',
    'account' => 'アカウント',
    'pay_mode' => '支払いモード',
    'payment_amount' => '支払金額',
    'old_password' => '以前のパスワード',
    'new_password' => '新しいパスワード',
    'repeat_password' => 'パスワードを再度入力してください',
    'name' => '名前',
    'message' => 'メッセージ',
    'reason' => '理由',
    'first_name' => 'ファーストネーム',
    'last_name' => '苗字',
    'otp' => 'OTP',
    'phone_number' => '電話番号',
    'order_id' => '注文ID',
  ),
  'size' => 
  array (
    'numeric' => ':attributeは :sizeである必要があります。',
    'file' => ':attributeは :sizeキロバイトである必要があります。',
    'string' => ':attributeは :size文字である必要があります。',
    'array' => ':attributeには :sizeアイテムが含まれている必要があります。',
  ),
  'min' => 
  array (
    'numeric' => ':attributeは少なくとも :minである必要があります。',
    'file' => ':attributeは少なくとも :minキロバイトである必要があります。',
    'string' => ':attributeは少なくとも :min文字である必要があります。',
    'array' => ':attributeには、少なくとも :minアイテムが必要です。',
  ),
  'max' => 
  array (
    'numeric' => ':attributeは :maxより大きくすることはできません。',
    'file' => ':attributeは、 :maxキロバイトを超えることはできません。',
    'string' => ':attributeは :max文字より大きくすることはできません。',
    'array' => ':attributeには、 :maxを超えるアイテムを含めることはできません。',
  ),
  'lte' => 
  array (
    'numeric' => ':attributeは :value以下である必要があります。',
    'file' => ':attributeは、 :valueキロバイト以下である必要があります。',
    'string' => ':attributeは、 :value文字以下である必要があります。',
    'array' => ':attributeには、 :valueを超えるアイテムを含めることはできません。',
  ),
  'lt' => 
  array (
    'numeric' => ':attributeは :valueより小さくなければなりません。',
    'file' => ':attributeは :valueキロバイト未満である必要があります。',
    'string' => ':attributeは :value文字未満である必要があります。',
    'array' => ':attributeのアイテムは :value未満である必要があります。',
  ),
  'gte' => 
  array (
    'numeric' => ':attributeは :value以上である必要があります。',
    'file' => ':attributeは、 :valueキロバイト以上である必要があります。',
    'string' => ':attributeは、 :value文字以上である必要があります。',
    'array' => ':attributeには、 :valueアイテム以上が必要です。',
  ),
  'gt' => 
  array (
    'numeric' => ':attributeは :valueより大きくなければなりません。',
    'file' => ':attributeは :valueキロバイトより大きくなければなりません。',
    'string' => ':attributeは :value文字より大きくなければなりません。',
    'array' => ':attributeには :value以上のアイテムが必要です',
  ),
  'between' => 
  array (
    'numeric' => ':attributeは、 :minと :maxの間にある必要があります。',
    'file' => ':attributeは、 :min〜 :maxキロバイトである必要があります。',
    'string' => ':attributeは、 :minと :maxの文字の間にある必要があります。',
    'array' => ':attributeは、 :minアイテムと :maxアイテムの間にある必要があります。',
  ),
  'accepted' => ':attributeを受け入れる必要があります。',
  'active_url' => ':attributeは有効なURLではありません。',
  'after' => ':attributeは、 :dateの後の日付である必要があります。',
  'after_or_equal' => ':attributeは、 :date以降の日付である必要があります。',
  'alpha' => ':attributeには文字のみを含めることができます。',
  'alpha_dash' => ':attributeには、文字、数字、ダッシュ、およびアンダースコアのみを含めることができます。',
  'alpha_num' => ':attributeには、文字と数字のみを含めることができます。',
  'array' => ':attributeは配列である必要があります。',
  'before' => ':attributeは、 :dateより前の日付である必要があります。',
  'before_or_equal' => ':attributeは、 :date以前の日付である必要があります。',
  'boolean' => ':attributeフィールドはtrueまたはfalseである必要があります。',
  'confirmed' => ':attributeの確認が一致しません。',
  'date' => ':attributeは有効な日付ではありません。',
  'date_equals' => ':attributeは、 :dateと同じ日付である必要があります。',
  'date_format' => ':attributeが :formatの形式と一致しません。',
  'different' => ':attributeと :otherは異なっている必要があります。',
  'digits' => ':attributeは :digits桁である必要があります。',
  'digits_between' => ':attributeは、 :minから :maxの数字の間でなければなりません。',
  'dimensions' => ':attributeの画像サイズが無効です。',
  'distinct' => ':attributeフィールドの値が重複しています。',
  'email' => ':attributeは有効な電子メールアドレスである必要があります。',
  'ends_with' => ':attributeは、次のいずれかで終了する必要があります： :values。',
  'exists' => '選択した :attributeは無効です。',
  'file' => ':attributeフィールドの値が重複しています。',
  'filled' => ':attributeフィールドには値が必要です。',
  'image' => ':attributeは画像である必要があります。',
  'in' => '選択した :attributeは無効です。',
  'in-array' => ':attributeフィールドは :otherには存在しません。',
  'integer' => ':attributeは整数である必要があります。',
  'ip' => ':attributeは有効なIPアドレスである必要があります。',
  'ipv4' => ':attributeは有効なIPv4アドレスである必要があります。',
  'ipv6' => ':attributeは有効なIPv6アドレスである必要があります。',
  'json' => ':attributeは有効なJSON文字列である必要があります。',
  'mimes' => ':attributeは、 :valuesタイプのファイルである必要があります。',
  'mimetypes' => ':attributeは、 :valuesタイプのファイルである必要があります。',
  'not_in' => '選択した :attributeは無効です。',
  'not_regex' => ':attribute形式が無効です。',
  'numeric' => ':attributeは数値である必要があります。',
  'password' => 'パスワードが正しくありません。',
  'present' => ':attributeフィールドが存在する必要があります。',
  'regex' => ':attribute形式が無効です。',
  'required' => ':attributeフィールドは必須です。',
  'required_if' => ':otherが :valueの場合、 :attributeフィールドは必須です。',
  'required_unless' => ':otherが :valuesにない限り、 :attributeフィールドは必須です。',
  'required_with' => ':valuesが存在する場合、 :attributeフィールドは必須です。',
  'required_with_all' => ':valuesが存在する場合、 :attributeフィールドは必須です。',
  'required_without' => ':valuesが存在しない場合、 :attributeフィールドは必須です。',
  'required_without_all' => ':valuesが存在しない場合、 :attributeフィールドは必須です。',
  'same' => ':attributeと :otherは一致する必要があります。',
  'string' => ':attributeは文字列である必要があります。',
  'timezone' => ':attributeは有効なゾーンである必要があります。',
  'unique' => ':attributeはすでに使用されています。',
  'uploaded' => ':attributeのアップロードに失敗しました。',
  'url' => ':attribute形式が無効です。',
  'uuid' => ':attributeは有効なUUIDである必要があります。',
  'email_not_exist' => 'メールが存在しません',
  'not_registerd_using_email' => 'メールで登録していないため、パスワードをリセットできません',
  'phone_number_exist' => '電話番号はすでに存在します',
)
                ;